
site_name: My Homelab
site_url: https://homelab.danielssilva.dev
site_author: Daniel Silva
site_description: Documentation for my personal homelab setup
repo_url: https://github.com/DanielSSilva/homelab
use_directory_urls: true

dev_addr: 127.0.0.1:8000

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
  # palette:
  #   - scheme: soft-green-light
  #     primary: custom
  #     accent: custom
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to dark mode

  #   - scheme: charcoal-orange-dark
  #     primary: custom
  #     accent: custom
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to light mode

  font:
    text: Roboto Mono
    code: Roboto Mono

  features:
    # - navigation.top
    # - navigation.tabs
    - toc.integrate
    - content.code.copy
    - content.code.select
    #- content.action.edit
    - content.tabs.link
    #- content.code.annotate
    - navigation.instant

extra_css:
  - stylesheets/custom-theme.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - meta
  # - pub-obsidian
  # - pub-minifier

nav:
  - Home: index.md

  - Docker:
    - Actual Budget: docker/actual-budget.md
    - Beszel: docker/beszel.md
    - Dozzle: docker/dozzle.md
    - Duplicacy: docker/duplicacy.md
    - Frigate: docker/frigate.md